from .afk import AFKBot
from .anime_compare import AnimeCompareBot
from .base import CommandBot
from .bomb_party import BombPartyBot
from .font import FontBot
from .guess import GuessBot
from .help import HelpBot
from .lastfm import LastFMBot
from .mw_dictionary import MWBot
from .pull import PullBot
from .reminder import ReminderBot
from .rps import RPSBot
from .settings import SettingsBot
from .static_data import StaticDataBot
from .timezone import TimezoneBot
from .trivia import TriviaBot
from .user_data import UserDataBot
from .osu import *
from .scramble import *
from .server_msg import ServerMessageHandlerBot
